# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
  - package-ecosystem: "gomod"
    directory: "/infr-project"
    schedule:
      interval: "daily"
      time: "02:30"
    ignore:
      - dependency-name: "github.com/ThreeDotsLabs/watermill"
    groups:
      hashicorp:
        patterns:
          - "github.com/hashicorp/*"
      aws:
        patterns:
          - "github.com/aws/*"
      azure:
        patterns:
          - "github.com/Azure/*"
      swaggo:
        patterns:
          - "github.com/swaggo/*"
  - package-ecosystem: "gomod"
    directory: "/aws-web"
    schedule:
      interval: "daily"
      time: "00:00"
    groups:
      aws:
        patterns:
          - "github.com/aws/*"
  - package-ecosystem: "gomod"
    directory: "/identity-center"
    schedule:
      interval: "daily"
      time: "00:30"
  - package-ecosystem: "gomod"
    directory: "/alphavantage-server"
    schedule:
      interval: "daily"
      time: "02:00"
  - package-ecosystem: "gomod"
    directory: "/tour"
    schedule:
      interval: "daily"
      time: "01:30"
    groups:
      aws:
        patterns:
          - "github.com/aws/*"
      openapi:
        patterns:
          - "github.com/go-openapi/*"
  - package-ecosystem: "gomod"
    directory: "/k8sbuilder"
    schedule:
      interval: "daily"
      time: "03:15"
    groups:
      k8s:
        patterns:
          - "k8s.io/*"

  - package-ecosystem: "gomod"
    directory: "/openai-web"
    schedule:
      interval: "daily"
      time: "01:00"
