# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/aws-web" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      aws:
        patterns:
        - "github.com/aws/aws-sdk-go-v2*" 

  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/identity-center" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/container"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/k8sbuilder"
    schedule:
      interval: "daily"
    groups:
      aws:
        patterns:
        - "k8s.io*" 

  - package-ecosystem: "gomod"
    directory: "/openai-web"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/tour"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/alphavantage-server"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/bolg-service"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/infr-project"
    schedule:
      interval: "daily"
