name: "syncdata"
description: "sync data for aws"

inputs:
  call:
    description: "call from github action"
    required: true
  mongodb_url:
    description: "mongodb url"
    required: true
  db_name:
    description: "mongodb name"
    required: true
  aws_config_sync:
    description: "aws config sync flag"
  accountid:
    description: "accountid" 

runs:
  using: docker
  image: Dockerfile 
  env:
    db_name: "${{ inputs.db_name }}"
    mongodb_url: "${{ inputs.mongodb_url }}"
    accountid: "${{ inputs.accountid }}"
    aws_config_sync: "${{ inputs.aws_config_sync }}"
  args:
  - "-call=${{ inputs.call }}"