name: "repository-clone"
description: "clone repository form 'source', and push to 'destination'"

inputs:
  owner:
    description: "source repository owner."
    required: true
  branch:
    description: "source repository branch."
    required: true
  name:
    description: "source repository name."
    required: true
  source_token:
    description: "source repository token."
    required: true
    
  dest_owner:
    description: "destination repository owner."
    required: true
  dest_branch:
    description: "destination repository branch."
    required: true
  dest_name:
    description: "destination repository name."
    required: true
  dest_token:
    description: "destination repository token."
    required: true

  step:
    description: "step."
    required: true

outputs:
  time:
    description: 'The time we greeted you'
  branch: 
    description: 'Git branch'

runs:
  using: docker
  image: Dockerfile
  env:
    source_token: "${{ inputs.source_token }}"
    dest_token: "${{ inputs.dest_token }}"
  args:
  - "-owner=${{ inputs.owner }}"
  - "-branch=${{ inputs.branch }}"
  - "-name=${{ inputs.name }}"
  
  - "-dest_owner=${{ inputs.dest_owner }}"
  - "-dest_branch=${{ inputs.dest_branch }}"
  - "-dest_name=${{ inputs.dest_name }}"

  - "-step=${{ inputs.step }}"