version: 2.1

parameters:
  aws-web:
    type: boolean
    default: false
  identity-center:
    type: boolean
    default: false
  openai-web:
    type: boolean
    default: false
  infr-project:
    type: boolean
    default: false
  alphavantage-server:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: cimg/go:1.21.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "<< parameters.path >>/go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
          working_directory: ~/goproject/<< parameters.path >>
      - save_cache:
          key: go-mod-v4-{{ checksum "<< parameters.path >>/go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/<< parameters.path >>/test-reports
            gotestsum --junitfile /tmp/<< parameters.path >>/test-reports/unit-tests.xml
          working_directory: ~/goproject/<< parameters.path >>
      - store_test_results:
          path: /tmp/<< parameters.path >>/test-reports
      - run:
          name: << parameters.path >> finish
          command: echo "<< parameters.path >> job finish"

workflows:
  aws-web:
    when: << pipeline.parameters.aws-web >>
    jobs:
      - build:
          name: aws-web-build
          path: aws-web
  identity-center:
    when: << pipeline.parameters.identity-center >>
    jobs:
      - build:
          name: identity-center-build
          path: identity-center
  openai-web:
    when: << pipeline.parameters.openai-web >>
    jobs:
      - build:
          name: openai-web-build
          path: openai-web
  infr-project:
    when: << pipeline.parameters.infr-project >>
    jobs:
      - build:
          name: infr-project-build
          path: infr-project
  alphavantage-server:
    when: << pipeline.parameters.alphavantage-server >>
    jobs:
      - build:
          name: alphavantage-server-build
          path: alphavantage-server
