version: 2.1

parameters:
  project-name:
    type: string
  project-path:
    type: string
  go-image:
    type: string
    default: "cimg/go:1.21.5"

jobs:
  go-build:
    working_directory: ~/goproject
    docker:
      - image: << parameters.go-image >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "<< parameters.project-path >>/go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
          working_directory: ~/goproject/<< parameters.project-path >>
      - save_cache:
          key: go-mod-v4-{{ checksum "<< parameters.project-path >>/go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/<< parameters.project-name >>/test-reports
            gotestsum --junitfile /tmp/<< parameters.project-name >>/test-reports/unit-tests.xml
          working_directory: ~/goproject/<< parameters.project-path >>
      - store_test_results:
          path: /tmp/<< parameters.project-name >>/test-reports
      - run:
          name: Finish
          command: echo "<< parameters.project-name >> job finish"
