# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

parameters:
  openai-web:
    type: boolean
    default: false

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  openai-web-build:
    working_directory: ~/goproject
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: circleci/golang:1.15.8
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout 
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "openai-web/go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
          working_directory: ~/goproject/openai-web
      - run:
          name: Build Project
          command: go build .
          working_directory: ~/goproject/openai-web
      - save_cache:
          key: go-mod-v4-{{ checksum "openai-web/go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/openai-web/test-reports
            gotestsum --junitfile /tmp/openai-web/test-reports/unit-tests.xml
          working_directory: ~/goproject/openai-web
      - store_test_results:
          path: /tmp/openai-web/test-reports
      - run:
          name: openai-web down
          command: echo "openai-web job finish"
          working_directory: ~/goproject/openai-web

# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  openai-web: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - openai-web-build
