definitions:
  platform.Platform:
    properties:
      activate:
        type: boolean
      name:
        type: string
      projects:
        additionalProperties:
          $ref: '#/definitions/platform.PlatformProject'
        type: object
      property:
        additionalProperties:
          type: string
        type: object
      rest_endpoint:
        type: string
      tags:
        items:
          type: string
        type: array
      url:
        type: string
    type: object
  platform.PlatformProject:
    properties:
      id:
        type: string
      name:
        type: string
      property:
        additionalProperties:
          type: string
        type: object
      url:
        type: string
      webhooks:
        items:
          $ref: '#/definitions/platform.Webhook'
        type: array
    type: object
  platform.Webhook:
    properties:
      activate:
        type: boolean
      name:
        type: string
      property:
        additionalProperties:
          type: string
        type: object
      state: {}
      url:
        type: string
    type: object
  project.Project:
    properties:
      description:
        type: string
      designs:
        items:
          $ref: '#/definitions/project.ProjectDesign'
        type: array
      end_date:
        type: string
      name:
        type: string
      platforms:
        items:
          $ref: '#/definitions/project.ProjectPlatform'
        type: array
      start_date:
        type: string
      state: {}
      tags:
        items:
          type: string
        type: array
    type: object
  project.ProjectDesign:
    properties:
      description:
        type: string
      name:
        type: string
      resources:
        description: ref resource.Resource
        items:
          type: string
        type: array
    type: object
  project.ProjectPlatform:
    properties:
      description:
        type: string
      name:
        type: string
      project_id:
        description: ref platform.PlatformProject
        type: string
    type: object
  resource.Resource:
    properties:
      created_at:
        type: string
      data:
        type: string
      is_deleted:
        type: boolean
      name:
        type: string
      tags:
        items:
          type: string
        type: array
      type: {}
      updated_at:
        type: string
    type: object
  viewmodels.CreatePlatformRequest:
    properties:
      name:
        maxLength: 50
        minLength: 3
        type: string
      property:
        additionalProperties:
          type: string
        type: object
      rest:
        maxLength: 50
        minLength: 3
        type: string
      tags:
        items:
          type: string
        type: array
      url:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - name
    - rest
    - url
    type: object
  viewmodels.CreateProjectRequest:
    properties:
      description:
        maxLength: 500
        minLength: 3
        type: string
      end_time:
        type: string
      name:
        maxLength: 50
        minLength: 3
        type: string
      start_time:
        type: string
      state:
        enum:
        - preparing
        - processing
        - finished
        type: string
      tags:
        items:
          type: string
        type: array
    required:
    - description
    - name
    type: object
  viewmodels.CreateResourceRequest:
    properties:
      data:
        minLength: 3
        type: string
      name:
        maxLength: 50
        minLength: 3
        type: string
      tags:
        items:
          type: string
        type: array
      type:
        enum:
        - DrawIO
        - Markdown
        - Excalidraw
        - Plate
        type: string
    required:
    - data
    - name
    type: object
  viewmodels.ResourceDetail:
    properties:
      created_at:
        type: string
      data:
        type: string
      id:
        type: string
      is_deleted:
        type: boolean
      name:
        type: string
      type:
        type: string
      updated_at:
        type: string
    type: object
  viewmodels.UpdatePlatformProjectRequest:
    properties:
      name:
        maxLength: 50
        minLength: 3
        type: string
      property:
        additionalProperties:
          type: string
        type: object
      url:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - name
    - url
    type: object
  viewmodels.UpdatePlatformRequest:
    properties:
      activate:
        type: boolean
      name:
        maxLength: 50
        minLength: 3
        type: string
      property:
        additionalProperties:
          type: string
        type: object
      rest:
        maxLength: 50
        minLength: 3
        type: string
      tags:
        items:
          type: string
        type: array
      url:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - name
    - rest
    - url
    type: object
  viewmodels.UpdatePlatformWebhookRequest:
    properties:
      activate:
        type: boolean
      name:
        maxLength: 50
        minLength: 3
        type: string
      property:
        additionalProperties:
          type: string
        type: object
      state:
        enum:
        - Init
        - Creating
        - Ready
        type: string
      url:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - activate
    - name
    - url
    type: object
  viewmodels.UpdateProjectDesignRequest:
    properties:
      description:
        maxLength: 500
        minLength: 3
        type: string
      name:
        maxLength: 50
        minLength: 3
        type: string
      resources:
        items:
          type: string
        type: array
    required:
    - name
    - resources
    type: object
  viewmodels.UpdateProjectPlatformRequest:
    properties:
      description:
        maxLength: 500
        minLength: 3
        type: string
      name:
        maxLength: 50
        minLength: 3
        type: string
      project_id:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - name
    - project_id
    type: object
  viewmodels.UpdateProjectRequest:
    properties:
      description:
        maxLength: 500
        minLength: 3
        type: string
      end_time:
        type: string
      name:
        maxLength: 50
        minLength: 3
        type: string
      start_time:
        type: string
      state:
        enum:
        - preparing
        - processing
        - finished
        type: string
      tags:
        items:
          type: string
        type: array
    type: object
  viewmodels.UpdateResourceRequest:
    properties:
      data:
        minLength: 3
        type: string
      name:
        maxLength: 50
        minLength: 3
        type: string
      tags:
        items:
          type: string
        type: array
    required:
    - data
    - name
    type: object
info:
  contact: {}
paths:
  /platform:
    get:
      consumes:
      - application/json
      description: get all platform
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/platform.Platform'
            type: array
      summary: get all platform
      tags:
      - Platform
    post:
      consumes:
      - application/json
      description: create platform
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/viewmodels.CreatePlatformRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: create platform
      tags:
      - Platform
  /platform/{id}:
    delete:
      consumes:
      - application/json
      description: delete platform
      parameters:
      - description: Platform ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: delete platform
      tags:
      - Platform
    get:
      consumes:
      - application/json
      description: get platform
      parameters:
      - description: Platform ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/platform.Platform'
      summary: get platform
      tags:
      - Platform
    put:
      consumes:
      - application/json
      description: update platform
      parameters:
      - description: Platform ID
        in: path
        name: id
        required: true
        type: string
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/viewmodels.UpdatePlatformRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: update platform
      tags:
      - Platform
  /platform/{id}/project:
    post:
      consumes:
      - application/json
      description: create platform webhook
      parameters:
      - description: Platform ID
        in: path
        name: id
        required: true
        type: string
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/viewmodels.UpdatePlatformProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: create platform webhook
      tags:
      - Platform
  /platform/{id}/project/{project_id}:
    delete:
      consumes:
      - application/json
      description: delete platform project
      parameters:
      - description: Platform ID
        in: path
        name: id
        required: true
        type: string
      - description: Platform Project ID
        in: path
        name: project_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: delete platform project
      tags:
      - Platform
    put:
      consumes:
      - application/json
      description: update platform project
      parameters:
      - description: Platform ID
        in: path
        name: id
        required: true
        type: string
      - description: Platform Project ID
        in: path
        name: project_id
        required: true
        type: string
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/viewmodels.UpdatePlatformProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: update platform project
      tags:
      - Platform
  /platform/{id}/project/{project_id}/hook:
    put:
      consumes:
      - application/json
      description: update platform webhook
      parameters:
      - description: Platform ID
        in: path
        name: id
        required: true
        type: string
      - description: Platform Project ID
        in: path
        name: project_id
        required: true
        type: string
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/viewmodels.UpdatePlatformWebhookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: update platform webhook
      tags:
      - Platform
  /project:
    get:
      consumes:
      - application/json
      description: get all project
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/project.Project'
            type: array
      summary: get all project
      tags:
      - Project
    post:
      consumes:
      - application/json
      description: create project
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/viewmodels.CreateProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: create project
      tags:
      - Project
  /project/{id}:
    get:
      consumes:
      - application/json
      description: get project
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/project.Project'
      summary: get project
      tags:
      - Project
    put:
      consumes:
      - application/json
      description: update project
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/viewmodels.UpdateProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: update project
      tags:
      - Project
  /project/{id}/design:
    put:
      consumes:
      - application/json
      description: update project design
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/viewmodels.UpdateProjectDesignRequest'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: update project design
      tags:
      - Project
  /project/{id}/platform:
    put:
      consumes:
      - application/json
      description: update project platform
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/viewmodels.UpdateProjectPlatformRequest'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: update project platform
      tags:
      - Project
  /resource:
    get:
      consumes:
      - application/json
      description: get all resources
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/viewmodels.ResourceDetail'
            type: array
      summary: get all resources
      tags:
      - Resource
    post:
      consumes:
      - application/json
      description: create resource
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/viewmodels.CreateResourceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: create resource
      tags:
      - Resource
  /resource/{id}:
    delete:
      consumes:
      - application/json
      description: delete resource
      parameters:
      - description: Resource ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: delete resource
      tags:
      - Resource
    get:
      consumes:
      - application/json
      description: get resource
      parameters:
      - description: Resource ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/viewmodels.ResourceDetail'
      summary: get resource
      tags:
      - Resource
    put:
      consumes:
      - application/json
      description: update resource
      parameters:
      - description: Resource ID
        in: path
        name: id
        required: true
        type: string
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/viewmodels.UpdateResourceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: update resource
      tags:
      - Resource
  /resource/{id}/history:
    get:
      consumes:
      - application/json
      description: get resource history
      parameters:
      - description: Resource ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/resource.Resource'
            type: array
      summary: get resource history
      tags:
      - Resource
swagger: "2.0"
