// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/futugyousuzu/identity-server/client (interfaces: IOAuthRequestRepository)

// Package client_test is a generated GoMock package.
package client_test

import (
	context "context"
	reflect "reflect"

	client "github.com/futugyousuzu/identity-server/client"
	gomock "go.uber.org/mock/gomock"
)

// MockIOAuthRequestRepository is a mock of IOAuthRequestRepository interface.
type MockIOAuthRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIOAuthRequestRepositoryMockRecorder
}

// MockIOAuthRequestRepositoryMockRecorder is the mock recorder for MockIOAuthRequestRepository.
type MockIOAuthRequestRepositoryMockRecorder struct {
	mock *MockIOAuthRequestRepository
}

// NewMockIOAuthRequestRepository creates a new mock instance.
func NewMockIOAuthRequestRepository(ctrl *gomock.Controller) *MockIOAuthRequestRepository {
	mock := &MockIOAuthRequestRepository{ctrl: ctrl}
	mock.recorder = &MockIOAuthRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOAuthRequestRepository) EXPECT() *MockIOAuthRequestRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIOAuthRequestRepository) Get(arg0 context.Context, arg1 string) (*client.AuthModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*client.AuthModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIOAuthRequestRepositoryMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIOAuthRequestRepository)(nil).Get), arg0, arg1)
}

// Insert mocks base method.
func (m *MockIOAuthRequestRepository) Insert(arg0 context.Context, arg1 *client.AuthModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockIOAuthRequestRepositoryMockRecorder) Insert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIOAuthRequestRepository)(nil).Insert), arg0, arg1)
}

// Update mocks base method.
func (m *MockIOAuthRequestRepository) Update(arg0 context.Context, arg1 *client.AuthModel, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIOAuthRequestRepositoryMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIOAuthRequestRepository)(nil).Update), arg0, arg1, arg2)
}
