definitions:
  app.Pager:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      totle_rows:
        type: integer
    type: object
  errcode.Error:
    type: object
  model.Tag:
    properties:
      created_by:
        type: string
      created_on:
        type: integer
      deleted_on:
        type: integer
      id:
        type: integer
      is_del:
        type: integer
      modified_by:
        type: string
      modified_on:
        type: integer
      name:
        type: string
      state:
        type: integer
    type: object
  model.TagSwagger:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      pager:
        $ref: '#/definitions/app.Pager'
        type: object
    type: object
info:
  contact: {}
  description: go project
  license: {}
  title: blog_service
paths:
  /api/v1/tags:
    get:
      parameters:
      - description: tag name
        in: query
        maxLength: 100
        name: name
        type: string
      - description: state
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: error
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: error
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: get tags
swagger: "2.0"
