# permissions for end users to view simpledeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8sbuilder
    app.kubernetes.io/managed-by: kustomize
  name: apps-simpledeployment-viewer-role
rules:
- apiGroups:
  - apps.vishel.io
  resources:
  - simpledeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.vishel.io
  resources:
  - simpledeployments/status
  verbs:
  - get
