# permissions for end users to edit configdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8sbuilder
    app.kubernetes.io/managed-by: kustomize
  name: apps-configdeployment-editor-role
rules:
- apiGroups:
  - apps.vishel.io
  resources:
  - configdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.vishel.io
  resources:
  - configdeployments/status
  verbs:
  - get
