# permissions for end users to view projectconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8sbuilder
    app.kubernetes.io/managed-by: kustomize
  name: config-projectconfig-viewer-role
rules:
- apiGroups:
  - config.vishel.io
  resources:
  - projectconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.vishel.io
  resources:
  - projectconfigs/status
  verbs:
  - get
