---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.vishel.io
  resources:
  - simpledeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.vishel.io
  resources:
  - simpledeployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps.vishel.io
  resources:
  - simpledeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - batch.vishel.io
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.vishel.io
  resources:
  - cronjobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.vishel.io
  resources:
  - cronjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.vishel.io
  resources:
  - guestbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.vishel.io
  resources:
  - guestbooks/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.vishel.io
  resources:
  - guestbooks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - webapp.vishel.io
  resources:
  - welcomes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.vishel.io
  resources:
  - welcomes/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.vishel.io
  resources:
  - welcomes/status
  verbs:
  - get
  - patch
  - update
