# permissions for end users to view guestbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8sbuilder
    app.kubernetes.io/managed-by: kustomize
  name: webapp-guestbook-viewer-role
rules:
- apiGroups:
  - webapp.vishel.io
  resources:
  - guestbooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.vishel.io
  resources:
  - guestbooks/status
  verbs:
  - get
