swagger: "2.0"
info:
  title: openai web API
  description: |
    provider some api for openai demo.
  version: 1.0.0
basePath: /api/v1
paths:
  /autio/transcription:
    post:
      tags:
      - autio
      description: |-
        create audio transcription
        <br>
      operationId: AudioController.CreateAudioTranscription
      parameters:
      - in: body
        name: body
        description: body for create audio transcription content
        required: true
        schema:
          $ref: '#/definitions/lib.CreateAudioTranscriptionRequest'
      - in: query
        name: request
        schema:
          $ref: '#/definitions/lib.CreateAudioTranscriptionRequest'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/lib.CreateAudioTranscriptionResponse'
  /autio/translation:
    post:
      tags:
      - autio
      description: |-
        create audio translation
        <br>
      operationId: AudioController.CreateAudioTranslation
      parameters:
      - in: body
        name: body
        description: body for create audio translation content
        required: true
        schema:
          $ref: '#/definitions/lib.CreateAudioTranslationRequest'
      - in: query
        name: request
        schema:
          $ref: '#/definitions/lib.CreateAudioTranslationRequest'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/lib.CreateAudioTranslationResponse'
  /chat/:
    post:
      tags:
      - chat
      description: |-
        create chat
        <br>
      operationId: ChatController.CreateChat
      parameters:
      - in: body
        name: body
        description: body for create chat content
        required: true
        schema:
          $ref: '#/definitions/lib.CreateChatCompletionRequest'
      - in: query
        name: request
        schema:
          $ref: '#/definitions/lib.CreateChatCompletionRequest'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/lib.CreateChatCompletionResponse'
  /completion/{settingName}:
    get:
      tags:
      - completion
      operationId: CompletionController.get settings
      parameters:
      - in: path
        name: settingName
        description: setting name
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/services.CompletionModel'
  /fine-tune/{fine_tune_id}/events:
    get:
      tags:
      - fine-tune
      description: |-
        get fine tune by fine_tune_id
        <br>
      operationId: FineTuneController.Get Fine Tune Events
      parameters:
      - in: path
        name: fine_tune_id
        description: The key for fine_tune
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/lib.ListFinetuneEventResponse'
        "403":
          description: fine_tune_id is empty
  /model/:
    get:
      tags:
      - model
      description: |-
        list model
        <br>
      operationId: ModelController.ListModel
      responses:
        "200":
          description: "{list model} \t[]string"
  /qa/:
    post:
      tags:
      - qa
      description: |-
        create q&a
        <br>
      operationId: QuestionController.Createq&a
      parameters:
      - in: body
        name: body
        description: body for create q&a content
        required: true
        schema:
          $ref: '#/definitions/models.QuestionAnswer'
      - in: query
        name: request
        schema:
          $ref: '#/definitions/models.QuestionAnswer'
      responses:
        "200":
          description: "{test} \tstring"
  /test/:
    get:
      tags:
      - test
      description: |-
        do the test
        <br>
      operationId: TestController.test openai lib
definitions:
  lib.CreateAudioTranscriptionRequest:
    title: CreateAudioTranscriptionRequest
    type: object
  lib.CreateAudioTranscriptionResponse:
    title: CreateAudioTranscriptionResponse
    type: object
  lib.CreateAudioTranslationRequest:
    title: CreateAudioTranslationRequest
    type: object
  lib.CreateAudioTranslationResponse:
    title: CreateAudioTranslationResponse
    type: object
  lib.CreateChatCompletionRequest:
    title: CreateChatCompletionRequest
    type: object
  lib.CreateChatCompletionResponse:
    title: CreateChatCompletionResponse
    type: object
  lib.ListFinetuneEventResponse:
    title: ListFinetuneEventResponse
    type: object
  models.Object:
    title: Object
    type: object
  models.QuestionAnswer:
    title: QuestionAnswer
    type: object
    properties:
      best_of:
        type: integer
        format: int32
      echo:
        type: boolean
      frequency_penalty:
        type: number
        format: float
      logprobs:
        type: integer
        format: int64
      max_tokens:
        type: integer
        format: int32
      presence_penalty:
        type: number
        format: float
      prompt:
        type: string
      stop:
        type: array
        items:
          type: string
      stream:
        type: boolean
      temperature:
        type: number
        format: float
      top_p:
        type: number
        format: float
  models.User:
    title: User
    type: object
  services.CompletionModel:
    title: CompletionModel
    type: object
    properties:
      best_of:
        type: integer
        format: int64
      frequency_penalty:
        type: number
        format: float
      max_tokens:
        type: integer
        format: int32
      model:
        type: string
      presence_penalty:
        type: number
        format: float
      prompt:
        type: string
      stop:
        type: array
        items:
          type: string
      temperature:
        type: integer
        format: int32
      top_p:
        type: integer
        format: int32
tags:
- name: model
  description: |
    Operations about Models
- name: chat
  description: |
    Operations about Chat
- name: fine-tune
  description: |
    Operations about fine tune
- name: autio
  description: |
    Operations about Chat
- name: qa
  description: |
    Operations about q&a
- name: test
  description: |
    Operations about test
- name: completion
  description: |
    Operations about Completion
