name: AWS Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_AWS_WEB_ID }}
on:
  push:
    branches:
      - master
    paths: 
    - 'aws-web/**'
    - '.github/workflows/aws-vercel-production.yaml'
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment:
      name: Production – aws-web
    env:
      working-directory: ./aws-web

    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@canary
        working-directory: ${{env.working-directory}}

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{env.working-directory}}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{env.working-directory}}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{env.working-directory}}