name: Dependabot auto
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Show Dependabot info
        run:  |
          echo  ${{ steps.metadata.outputs.dependency-names }} 
          echo  ${{ steps.metadata.outputs.dependency-type }} 
          echo  ${{ steps.metadata.outputs.update-type }} 
          echo  ${{ steps.metadata.outputs.updated-dependencies-json }} 
          echo  ${{ steps.metadata.outputs.directory }} 
          echo  ${{ steps.metadata.outputs.package-ecosystem }} 
          echo  ${{ steps.metadata.outputs.target-branch }} 
          echo  ${{ steps.metadata.outputs.previous-version }} 
          echo  ${{ steps.metadata.outputs.new-version }} 
          echo  ${{ steps.metadata.outputs.alert-state }} 
          echo  ${{ steps.metadata.outputs.cvss }} 
          echo  ${{ steps.metadata.outputs.compatibility-score }} 
          echo  ${{ steps.metadata.outputs.maintainer-changes }} 
          echo  ${{ steps.metadata.outputs.dependency-group }} 