name: Fake Preview Deployment
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
    paths: 
    - 'tour/**'
    - 'k8sbuilder/**'
    - 'container/**'
    - '.github/workflows/empty-preview.yaml'
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment:
      name: Preview – fake

    steps:
      - uses: actions/checkout@v4
      
      - name: Tour
        run: go mod tidy && go build .
        working-directory: ./tour
      
      - name: K8sbuilder
        run: go mod tidy && go build ./cmd/main.go
        working-directory: ./k8sbuilder
      
      - name: Container
        run:  go mod tidy && go build -o mindocker .
        working-directory: ./container
        