name: Identity Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_IDENTITY_CENTER_ID }}
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
    paths: 
    - 'identity-center/**'
    - '.github/workflows/identity-vercel-preview.yaml'
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment:
      name: Preview – identity-center
    env:
      working-directory: ./identity-center

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
        working-directory: ${{env.working-directory}}

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{env.working-directory}}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{env.working-directory}}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{env.working-directory}}