name: Identity Vercel Preview Deployment

on:
  workflow_dispatch:
    inputs:
      go-version:
        description: "Go version"
        required: false
        default: "1.23"
      vercel-cli-version:
        description: "Vercel CLI version"
        required: false
        default: "47.1.4"
      install-go:
        description: "Whether to install the specified Go version"
        required: false
        default: "true"
  schedule:
  - cron: '40 22 * * *'
  push:
    branches-ignore:
      - master
    paths: 
    - 'identity-center/**'
    - '.github/workflows/identity-vercel-preview.yaml'

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_IDENTITY_CENTER_ID }}
  GO_VERSION: ${{ github.event.inputs.go-version || '1.24' }}
  VERCEL_CLI_VERSION: ${{ github.event.inputs.vercel-cli-version || '47.1.4' }}
  INSTALL_GO: ${{ github.event.inputs.install-go || 'true' }
  working-directory: ./identity-center

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment:
      name: Preview – identity-center

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        if: ${{ env.INSTALL_GO == 'true' }}
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Vercel CLI
        run: npm i -g vercel@${{ env.VERCEL_CLI_VERSION }}
        working-directory: ${{ env.working-directory }}

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{env.working-directory}}

      - name: Build Project Artifacts
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 vercel build --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{env.working-directory}}

      - name: Deploy Project Artifacts to Vercel
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{env.working-directory}}