name: OpenAI Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_OPENAI_WEB_ID }}
on:
  workflow_dispatch:
  schedule:
  - cron: '20 22 * * *'
  push:
    branches-ignore:
      - master
    paths: 
    - 'openai-web/**'
    - '.github/workflows/openAI-vercel-preview.yaml'
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment:
      name: Preview – openai-web
    env:
      working-directory: ./openai-web

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Vercel CLI
        run: npm install --global vercel@33.2.0
        working-directory: ${{env.working-directory}}

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{env.working-directory}}

      - name: Build Project Artifacts
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 vercel build --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{env.working-directory}}

      - name: Deploy Project Artifacts to Vercel
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ${{env.working-directory}}