name: repository-info

on:
 workflow_dispatch:
 # schedule:
 # - cron: '30 18 * * *'
jobs: 
  repository-info-action:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-output.outputs.result }}
    steps:
      - uses: actions/checkout@v4 
          
      - uses: ./github-actions/repository-info@main
        id: repository-info
        with:
          token: '${{ secrets.SOURCE_REPO_TOKEN }}'  
          
      - name: set output
        id: set-output
        run: |
          echo result=$(echo '${{ env.result }}' | jq .) >> $GITHUB_ENV
          echo "result=$result" >> $GITHUB_OUTPUT

  call-repository-clone: 
    uses: ./.github/workflows/repository-clone.yml@main
    needs: repository-info-action 
    name: ${{ matrix.repos.name }} 
    strategy:
      max-parallel: 3
      matrix:
        repos: ${{ fromJson(needs.repository-info-action.outputs.result) }}
    with:
      owner: ${{ matrix.repos.owner }}
      branch: ${{ matrix.repos.branch }}
      name: ${{ matrix.repos.name }}
    secrets: inherit
