name: repository-clone

on:
  workflow_dispatch: 
    inputs:
      owner:
        required: true
        description: 'The repository owner'
        type: string
      branch:
        required: true
        description: 'The repository branch'
        type: string
      name:
        required: true
        description: 'The repository name'
        type: string 
  workflow_call:
    inputs:
      owner:
        required: true
        description: 'The repository owner'
        type: string
      branch:
        required: true
        description: 'The repository branch'
        type: string
      name:
        required: true
        description: 'The repository name'
        type: string
    secrets:
      SOURCE_REPO_TOKEN:
        required: true
      DEST_REPO_TOKEN:
        required: true
        
jobs: 
  clone:
    runs-on: ubuntu-latest
    steps:        
      - name: step 1
        uses: ./github-actions/repository-clone@main 
        with:
          owner: '${{ inputs.owner }}'  
          branch: '${{ inputs.branch }}'  
          name: '${{ inputs.name }}'  

          dest_owner: health-ecology
          dest_branch: master
          dest_name: '${{ inputs.name }}'  
          
          source_token: '${{ secrets.SOURCE_REPO_TOKEN }}' 
          dest_token: '${{ secrets.DEST_REPO_TOKEN }}'
          step: 1

      - name:  step 2
        run: |
          sudo rm -rf ./sourcerepositoryfolder/.git
          sudo cp -r  sourcerepositoryfolder/.github . 2>/dev/null || :
          sudo cp -r  sourcerepositoryfolder/* . 2>/dev/null || :
          sudo rm -rf ./sourcerepositoryfolder 
                  
      - name: step 3
        uses: ./github-actions/repository-clone@main 
        with:
          owner: '${{ inputs.owner }}'  
          branch: '${{ inputs.branch }}'  
          name: '${{ inputs.name }}'  

          dest_owner: health-ecology
          dest_branch: master
          dest_name: '${{ inputs.name }}'  
          
          source_token: '${{ secrets.SOURCE_REPO_TOKEN }}' 
          dest_token: '${{ secrets.DEST_REPO_TOKEN }}'
          step: 3
